<a href="https://colab.research.google.com/github/anushka-1318/data-science/blob/main/3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Create a 3x3 square matrix
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original Matrix A:")
print(matrix_a)

# Compute its determinant
determinant_a = np.linalg.det(matrix_a)

print(f"\nDeterminant of Matrix A: {determinant_a:.2f}")


Original Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix A: 0.00


b) Find the inverse of the matrix.



c) Solve the following system of linear equations using NumPy:

2x+3y=10 4x+5y=20



In [9]:
import numpy as np

# Define the matrix A from the user's input
A = np.array([
    [2, 3],
    [4, 5]
])

print("Original Matrix A:")
print(A)

# Compute its determinant
determinant_A = np.linalg.det(A)

print(f"\nDeterminant of Matrix A: {determinant_A:.2f}")

# Check if the determinant is close to zero (singular matrix)
if np.isclose(determinant_A, 0):
    print("\nMatrix A is singular (determinant is approximately zero) and therefore does not have an inverse.")
else:
    # Compute the inverse of the matrix
    inverse_A = np.linalg.inv(A)

    print("\nInverse of Matrix A:")
    print(inverse_A)

    # Verify the inverse (A @ A_inv should be close to identity matrix)
    identity_check = A @ inverse_A
    print("\nVerification (A @ A_inv):")
    print(identity_check)

Original Matrix A:
[[2 3]
 [4 5]]

Determinant of Matrix A: -2.00

Inverse of Matrix A:
[[-2.5  1.5]
 [ 2.  -1. ]]

Verification (A @ A_inv):
[[1. 0.]
 [0. 1.]]
