<a href="https://colab.research.google.com/github/anushka-1318/data-science/blob/main/matrixoperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#3*3 matrix
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

print("Matrix A:")
print(A)
a,b,c = A[0]
d,e,f = A[1]
g,h,i = A[2]
determinant = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)
print("\nDeterminant of A:", determinant)
if determinant != 0:
    C = np.array([
        [(e*i - f*h), -(d*i - f*g), (d*h - e*g)],
        [-(b*i - c*h), (a*i - c*g), -(a*h - b*g)],
        [(b*f - c*e), -(a*f - c*d), (a*e - b*d)]
    ])

    adj_A = C.T
    inv_A = adj_A / determinant

    print("\nInverse of A :")
    print(inv_A)
else:
    print("Inverse not possible (Determinant = 0)")
# 2x + 3y = 10
# 4x + 5y = 20

coef = np.array([[2, 3],
                 [4, 5]])

const = np.array([10, 20])

print("\nCoefficient Matrix:")
print(coef)
print("Constant Matrix:")
print(const)

a,b = coef[0]
c,d = coef[1]
e,f = const
D = a*d - b*c
Dx = e*d - b*f
Dy = a*f - e*c
x = Dx / D
y = Dy / D
print("\nSolution using Cramer's Rule:")
print("x =", x)
print("y =", y)

Matrix A:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Determinant of A: 1

Inverse of A :
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Coefficient Matrix:
[[2 3]
 [4 5]]
Constant Matrix:
[10 20]

Solution using Cramer's Rule:
x = 5.0
y = -0.0
